<?php
declare(strict_types=1);

return [
    ['GET', '/admin', [\Laas\Modules\Admin\Controller\DashboardController::class, 'index']],
    ['GET', '/admin/modules', [\Laas\Modules\Admin\Controller\ModulesController::class, 'index']],
    ['POST', '/admin/modules/toggle', [\Laas\Modules\Admin\Controller\ModulesController::class, 'toggle']],
    ['GET', '/admin/settings', [\Laas\Modules\Admin\Controller\SettingsController::class, 'index']],
    ['POST', '/admin/settings', [\Laas\Modules\Admin\Controller\SettingsController::class, 'save']],
    ['GET', '/admin/users', [\Laas\Modules\Admin\Controller\UsersController::class, 'index']],
    ['POST', '/admin/users/status', [\Laas\Modules\Admin\Controller\UsersController::class, 'toggleStatus']],
    ['POST', '/admin/users/admin', [\Laas\Modules\Admin\Controller\UsersController::class, 'toggleAdmin']],
    ['POST', '/admin/users/password', [\Laas\Modules\Admin\Controller\UsersController::class, 'changePassword']],
    ['POST', '/admin/users/delete', [\Laas\Modules\Admin\Controller\UsersController::class, 'delete']],
    ['GET', '/admin/users/roles', [\Laas\Modules\Admin\Controller\RolesController::class, 'index']],
    ['GET', '/admin/users/roles/new', [\Laas\Modules\Admin\Controller\RolesController::class, 'createForm']],
    ['GET', '/admin/users/roles/{id:\d+}/edit', [\Laas\Modules\Admin\Controller\RolesController::class, 'editForm']],
    ['POST', '/admin/users/roles/save', [\Laas\Modules\Admin\Controller\RolesController::class, 'save']],
    ['POST', '/admin/users/roles/delete', [\Laas\Modules\Admin\Controller\RolesController::class, 'delete']],
    ['GET', '/admin/users/roles/{id:\d+}/clone', [\Laas\Modules\Admin\Controller\RolesController::class, 'cloneForm']],
    ['POST', '/admin/users/roles/{id:\d+}/clone', [\Laas\Modules\Admin\Controller\RolesController::class, 'clone']],
    ['GET', '/admin/audit', [\Laas\Modules\Admin\Controller\AuditController::class, 'index']],
    ['GET', '/admin/ops', [\Laas\Modules\Admin\Controller\OpsController::class, 'index']],
    ['GET', '/admin/ops.json', [\Laas\Modules\Admin\Controller\OpsController::class, 'index']],
    ['GET', '/admin/ops/refresh', [\Laas\Modules\Admin\Controller\OpsController::class, 'refresh']],
    ['GET', '/admin/ai', [\Laas\Modules\Admin\Controller\AdminAiController::class, 'index']],
    ['POST', '/admin/ai/save-proposal', [\Laas\Modules\Admin\Controller\AdminAiController::class, 'saveProposal']],
    ['POST', '/admin/ai/dev-autopilot', [\Laas\Modules\Admin\Controller\AdminAiController::class, 'devAutopilot']],
    ['GET', '/admin/security-reports', [\Laas\Modules\Admin\Controller\SecurityReportsController::class, 'index']],
    ['GET', '/admin/security-reports/{id:\d+}', [\Laas\Modules\Admin\Controller\SecurityReportsController::class, 'show']],
    ['POST', '/admin/security-reports/{id:\d+}/triage', [\Laas\Modules\Admin\Controller\SecurityReportsController::class, 'triage']],
    ['POST', '/admin/security-reports/{id:\d+}/ignore', [\Laas\Modules\Admin\Controller\SecurityReportsController::class, 'ignore']],
    ['POST', '/admin/security-reports/{id:\d+}/delete', [\Laas\Modules\Admin\Controller\SecurityReportsController::class, 'delete']],
    ['GET', '/admin/api-tokens', [\Laas\Modules\Admin\Controller\ApiTokensController::class, 'index']],
    ['POST', '/admin/api-tokens', [\Laas\Modules\Admin\Controller\ApiTokensController::class, 'create']],
    ['POST', '/admin/api-tokens/rotate', [\Laas\Modules\Admin\Controller\ApiTokensController::class, 'rotate']],
    ['POST', '/admin/api-tokens/revoke', [\Laas\Modules\Admin\Controller\ApiTokensController::class, 'revoke']],
    ['GET', '/admin/api/tokens', [\Laas\Modules\Admin\Controller\ApiTokensController::class, 'index']],
    ['POST', '/admin/api/tokens', [\Laas\Modules\Admin\Controller\ApiTokensController::class, 'create']],
    ['POST', '/admin/api/tokens/rotate', [\Laas\Modules\Admin\Controller\ApiTokensController::class, 'rotate']],
    ['POST', '/admin/api/tokens/revoke', [\Laas\Modules\Admin\Controller\ApiTokensController::class, 'revoke']],
    ['GET', '/admin/search', [\Laas\Modules\Admin\Controller\AdminSearchController::class, 'index']],
    ['GET', '/admin/rbac/diagnostics', [\Laas\Modules\Admin\Controller\RbacDiagnosticsController::class, 'index']],
    ['POST', '/admin/rbac/diagnostics/check', [\Laas\Modules\Admin\Controller\RbacDiagnosticsController::class, 'checkPermission']],
];
